[env:lilygo-t3]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
    mcci-catena/MCCI LoRaWAN LMIC library
    https://github.com/RobTillaart/SHT85.git

build_flags =
    -D CFG_eu868=1
    -D CFG_sx1276_radio=1
    -D ARDUINO_LMIC_PROJECT_CONFIG_H_SUPPRESS
    -D CORE_DEBUG_LEVEL=0